# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RikingCalendar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RikingCalendar

  target 'RikingCalendarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RikingCalendarUITests' do
    inherit! :search_paths
    # Pods for testing
  end


pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8’
pod 'SDCycleScrollView','~> 1.64'
pod 'SlideMenuControllerOC'
pod 'IQKeyboardManagerSwift', '4.0.10'
pod 'FSCalendar'
pod 'Masonry'
pod 'FMDB'
end
